# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bridge_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from .paintwidget import PaintWidget
from .acquisition import Discovery
from .analysis import Analysis
import time
import pyqtgraph as pg
from pyqtgraph import PlotWidget
class BridgeWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super(BridgeWindow, self).__init__(*args, **kwargs)
        self.ui = Ui_bridge_main()
        self.ui.setupUi(self)
        self.setup()

    def setup(self):
        self.ui.pushButton.clicked.connect(self.fun_load_streams)

    def normalize(self):
        self.norm = Analysis(discovery=self.discovery, mode=None, OSC_params=None,
                             weight=None, manual_params=None, auto_params=None)
        self.norm.start()
        self.ui.console.append(str(self.norm.mess))

    def fun_load_streams(self):
        """
        button 2. Scan for LSL streams
        """
        # discover streams
        self.discovery = Discovery(
            discard_timestamps=True,
            correct_timestamps=False
        )
        self.discovery.start()
        time.sleep(3)
        streams = list(self.discovery.streams_by_uid.keys())

        # show info
        for n_row, id in enumerate(streams):
            self.ui.console.append(str(id))
            self.ui.console.append(str(self.discovery.channel_count))
        self.normalize()

class Ui_bridge_main(object):
    def setupUi(self, bridge_main):
        bridge_main.setObjectName("bridge_main")
        bridge_main.resize(548, 636)
        self.centralwidget = QtWidgets.QWidget(bridge_main)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PaintWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 511, 201))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.console = QtWidgets.QTextBrowser(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(30, 540, 211, 51))
        self.console.setObjectName("console")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 340, 411, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 141, 91))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_auto2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_auto2.setObjectName("label_auto2")
        self.gridLayout_5.addWidget(self.label_auto2, 3, 0, 1, 1)
        self.label_autow = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_autow.setObjectName("label_autow")
        self.gridLayout_5.addWidget(self.label_autow, 0, 0, 1, 1)
        self.label_auto1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_auto1.setObjectName("label_auto1")
        self.gridLayout_5.addWidget(self.label_auto1, 2, 0, 1, 1)
        self.horizontalSlider_auto2 = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.horizontalSlider_auto2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_auto2.setObjectName("horizontalSlider_auto2")
        self.gridLayout_5.addWidget(self.horizontalSlider_auto2, 3, 1, 1, 1)
        self.horizontalSlider_autow = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.horizontalSlider_autow.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_autow.setObjectName("horizontalSlider_autow")
        self.gridLayout_5.addWidget(self.horizontalSlider_autow, 0, 1, 1, 1)
        self.horizontalSlider_auto1 = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.horizontalSlider_auto1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_auto1.setObjectName("horizontalSlider_auto1")
        self.gridLayout_5.addWidget(self.horizontalSlider_auto1, 2, 1, 1, 1)
        self.horizontalSlider_autolag = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.horizontalSlider_autolag.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_autolag.setObjectName("horizontalSlider_autolag")
        self.gridLayout_5.addWidget(self.horizontalSlider_autolag, 1, 1, 1, 1)
        self.label_autolag = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_autolag.setObjectName("label_autolag")
        self.gridLayout_5.addWidget(self.label_autolag, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 141, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_man2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_man2.setObjectName("label_man2")
        self.gridLayout_6.addWidget(self.label_man2, 3, 0, 1, 1)
        self.label_manw = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_manw.setObjectName("label_manw")
        self.gridLayout_6.addWidget(self.label_manw, 0, 0, 1, 1)
        self.label_man1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_man1.setObjectName("label_man1")
        self.gridLayout_6.addWidget(self.label_man1, 2, 0, 1, 1)
        self.horizontalSlider_man2 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_man2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_man2.setObjectName("horizontalSlider_man2")
        self.gridLayout_6.addWidget(self.horizontalSlider_man2, 3, 1, 1, 1)
        self.horizontalSlider_manw = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_manw.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_manw.setObjectName("horizontalSlider_manw")
        self.gridLayout_6.addWidget(self.horizontalSlider_manw, 0, 1, 1, 1)
        self.horizontalSlider_man1 = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_man1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_man1.setObjectName("horizontalSlider_man1")
        self.gridLayout_6.addWidget(self.horizontalSlider_man1, 2, 1, 1, 1)
        self.horizontalSlider_manlag = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_manlag.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_manlag.setObjectName("horizontalSlider_manlag")
        self.gridLayout_6.addWidget(self.horizontalSlider_manlag, 1, 1, 1, 1)
        self.label_manlag = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_manlag.setObjectName("label_manlag")
        self.gridLayout_6.addWidget(self.label_manlag, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.comboBox_mode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_mode.setGeometry(QtCore.QRect(140, 270, 60, 22))
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.label_mode = QtWidgets.QLabel(self.centralwidget)
        self.label_mode.setGeometry(QtCore.QRect(30, 270, 111, 31))
        self.label_mode.setObjectName("label_mode")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 240, 271, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 251, 25))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_7.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_open = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout_7.addWidget(self.pushButton_open, 0, 0, 1, 1)
        self.checkBox_file = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_file.setGeometry(QtCore.QRect(10, 20, 131, 18))
        self.checkBox_file.setObjectName("checkBox_file")
        self.horizontalSlider_weight = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_weight.setGeometry(QtCore.QRect(70, 310, 141, 16))
        self.horizontalSlider_weight.setMaximum(10)
        self.horizontalSlider_weight.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_weight.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_weight.setTickInterval(1)
        self.horizontalSlider_weight.setObjectName("horizontalSlider_weight")
        self.label_weight = QtWidgets.QLabel(self.centralwidget)
        self.label_weight.setGeometry(QtCore.QRect(30, 310, 47, 14))
        self.label_weight.setObjectName("label_weight")
        bridge_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(bridge_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 22))
        self.menubar.setObjectName("menubar")
        bridge_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(bridge_main)
        self.statusbar.setObjectName("statusbar")
        bridge_main.setStatusBar(self.statusbar)

        self.retranslateUi(bridge_main)
        QtCore.QMetaObject.connectSlotsByName(bridge_main)

    def retranslateUi(self, bridge_main):
        _translate = QtCore.QCoreApplication.translate
        bridge_main.setWindowTitle(_translate("bridge_main", "MainWindow"))
        self.pushButton.setText(_translate("bridge_main", "display"))
        self.groupBox_2.setTitle(_translate("bridge_main", "Auto"))
        self.label_auto2.setText(_translate("bridge_main", "min"))
        self.label_autow.setText(_translate("bridge_main", "window"))
        self.label_auto1.setText(_translate("bridge_main", "max"))
        self.label_autolag.setText(_translate("bridge_main", "lag"))
        self.groupBox_3.setTitle(_translate("bridge_main", "from file"))
        self.label_man2.setText(_translate("bridge_main", "min"))
        self.label_manw.setText(_translate("bridge_main", "window"))
        self.label_man1.setText(_translate("bridge_main", "max"))
        self.label_manlag.setText(_translate("bridge_main", "lag"))
        self.comboBox_mode.setItemText(0, _translate("bridge_main", "MinMax"))
        self.comboBox_mode.setItemText(1, _translate("bridge_main", "zscore"))
        self.label_mode.setText(_translate("bridge_main", "Normalization mode"))
        self.groupBox_4.setTitle(_translate("bridge_main", "baseline file"))
        self.pushButton_open.setText(_translate("bridge_main", "Open..."))
        self.checkBox_file.setText(_translate("bridge_main", "use a file for baselining"))
        self.label_weight.setText(_translate("bridge_main", "weight"))




